### ISSUE TITLE
Login on new devices via QR code

### ISSUE THREAD

**Issue by stefanopepe** [near/near-wallet-roadmap#16]
**Summary**
Today, users can open their wallet on a new browser/device by using the seed passphrase - which instead should be used only for recovery needs.
This feature will enable other devices to sign a transaction and authorize a new wallet without the need to expose the recovery seed.

**Intended Outcome**
As a user, I want to open my wallet on a new device bypassed  using a previously enabled device, such that I don't have to type the seed passphrase or recover it via email/SMS

**How will it work?**
Users will be presented with a login button that, similarly to Whatsapp and Telegram web-interfaces, enables the user to scan a QR code from their already-authenticated mobile device, and authorize the wallet in the browser.
This process will leverage the existing key authorization schema, so the backend and the APIs will remain the same.
Overall, the goal is to reduce the need for the seed passphrase when the user doesn't need to recover their wallet.

**Comment by Patrick1904** [comment]
Closing as this feature was shipped here: https://github.com/near/near-wallet/pull/2038

Feature is currently only available on Testnet (wallet.testnet.near.org)
