### ISSUE TITLE
Highlight apps on NEAR (V1)

### ISSUE THREAD

**Issue by jimmy3dita** [near/near-wallet-roadmap#18]
**Summary**
Users will see a call to action to try NEAR apps as soon as they complete their onboarding and land on the wallet main screen.

**Intended Outcome**
As a just-onboarded user, I want to see a small list of NEAR apps, such that I can quickstart my experience in the ecosystem.

The success of this feature will be measured against the number of active users successfully handed-over to the ecosystem, and their monetary value 

**How will it work?**
Since this feature has a partial overlapping with awesomenear.com, the initial version may use the empty "authorized apps" in the wallet home to suggest some apps to try. The final UX/UI is subject to change after the design phase of this feature.

**Comment by corwinharrell** [comment]
Here is a link for the WIP prototype. Will continue to add to this but figured I'd put it here for people to check out:

https://www.figma.com/proto/y1kyUHVr11lUmDkDSzMKU8/Create-New-Account?node-id=91%3A807&viewport=-591%2C586%2C0.8091995120048523&scaling=scale-down

**Comment by jimmy3dita** [comment]
This proposal had a wow effect on me! I like it!
Where do we pull the detailed information? Is ok if we parse it from awesomenear.com?

**Comment by corwinharrell** [comment]
@jimmy3dita I think that's ok for now? Alternatively we can add the content ourselves, which I'd be happy to do.

**Comment by corwinharrell** [comment]
The first iteration of this is going to be a simple banner that we display to users on the primary wallet dashboard, and is being implemented as a part of https://github.com/near/near-wallet/pull/1470

<img width="235" alt="Screen Shot 2021-02-24 at 12 39 58 PM" src="https://user-images.githubusercontent.com/5934188/109041804-6d434400-769d-11eb-8cd8-518c50f62bdd.png">

**Comment by jimmy3dita** [comment]
Looks great to me! Ideally we can pull the content from awesomenear.com - otherwise we can also work with a simple markdown or json that is easy to edit. 
It's important that we don't embed this information too deep into the code, to keep maintenance super lightweight cc @Patrick1904
