### ISSUE TITLE
Use MoonPay to refill the account balance

### ISSUE THREAD

**Issue by jimmy3dita** [near/near-wallet-roadmap#19]
**Summary**
Today, users can add funds to their wallet by opening their exchange account, and go through the process of buying tokens and transferring them.
With this feature, users are enabled to use Moonpay to fund their existing account - repeating the process that before was available only at the account creation.

**Intended Outcome**
As a user, I want to add funds to my wallet balance without leaving NEAR wallet user experience.

The success of this feature will be measured against the number of transactions performed within the application.

**How will it work?**
Similarly to #5, users have a way to add funds to their balance, by using their credit card and the Moonpay buy process. 
As a nice-to-have, we may enable this functionality via deep-linking, such that third-party applications can call this feature from their user interface.

**Comment by vgrichina** [comment]
I think this is shipped already:
https://github.com/near/near-wallet/pull/1607
