### ISSUE TITLE
Scan QR code to get NFT  and then shows the white screen 

### ISSUE THREAD

**Issue by RubyJiao** [near/near-wallet-roadmap#27]
After the new users in China scanned QR code to get NFT and opened the link with android system browser (huawei, xiaomi,meizu,oppo and so on), the screen remained nothing just become a white screen and the register or log in page did not appear. Both wifi and 4G did not work. And when the users registered with email, it took about 2 or 3 minutes to get the verification code(both ios or android system). It takes to long and the experience of users is not good enough. We could do some optimization.

**Comment by think-in-universe** [comment]
thanks for submitting the issue, Ruby  @RubyJiao 

Please submitted it to this repository. https://github.com/near/near-wallet
