### ISSUE TITLE
Fiat currency value of the wallet

### ISSUE THREAD

**Issue by stefanopepe** [near/near-wallet-roadmap#28]
**Summary**
With the goal to improve user experience and product stickiness, NEAR Wallet will show a real-time price conversion to common fiat currencies - both for the wallet balance and the transactions.

**Intended Outcome**
NEAR Wallet will help end-users to measure, in fiat value, transactions and holdings in their wallet.
The outcome, from a user perspective, is better understanding of the owned assets. From a wallet/product perspective, this functionality will increase the engagement, and the return of users - even if they are not interested to send transactions or perform wallet-related activities.

This feature will positively influence the stickiness of the product (DAU/MAU coefficient) and the overall usability/satisfaction of the user base.

**How will it work**
A backend service will regularly query a price ticker, and will simply multiply the exchange rate by the total tokens (held in the wallet, or subject of a transaction).
Some optimizations will keep the price ticker "fixed" unless the user reloads the page, to partially mitigate the micro-volatility  of NEAR tokens over time.
The first iteration will include USD values, but (depending on the API and the demand) other currencies may be quickly added - enabling users to select the favorite one and keep it as a preference.

**Comment by corwinharrell** [comment]
@stefanopepe as a start we could look at wallet usage in the top 3-5 geographies and priorities offering those conversions initially (Chinese Yuan for example)
